#!/usr/bin/env bash

TEMPDIRPATH=${DATADIR}/tempdir/portage

expect -2 -s "*'
work
extra line'" -c1P "${TEMPDIRPATH}" --no-capture --run="${BASH}" test <<<'
	echo something
	echo ${PWD##*/}
	echo extra line'

xfail 100 expect -2 -s "*' - dev-test test dev-test/test'" \
	-c1P "${TEMPDIRPATH}" -R "${BASH}" test <<<'
	echo "${WCD_CATEGORY} ${WCD_P} ${WCD_PACKAGE}"
	exit 100'

expect -2 -! "*badoutput*" -c1P "${TEMPDIRPATH}" --no-command -sR "${BASH}" test <<<'
	echo badoutput'

HOME=${PWD}/home
mkdir home
echo -n 'hello' > home/file1
echo -n ' world' > home/file2
echo 'cat "${1}" "${3}"; echo "${2}"' > home/testcmd
chmod +x home/testcmd
expect -2 "*hello world!*" -c1P "${TEMPDIRPATH}" --run="~/testcmd ~/file1 ! ~/file2" test
