#!/usr/bin/env bash
# verify that the original patch is not getting modified when it shouldn't
copydat normal.patch
expect -2 "Would*" -c --in-place --dry-run normal.patch
xfail 1 expect -2 "*Error:*invalid arguments*" -c --in-place --unrecognized-option normal.patch
expect "Header*" -c --stdout normal.patch
md5cmp 93034dc9e991b20e6cba008583fb14d0 normal.patch
