#!/usr/bin/env bash
# * 014,015,025,026,055,063: not using git-style a/ b/
# * 051: over 20 lines removed in a row
# * 056: removed file
# * 063: configure file
# * 072: flat pkg-config
# * 073: top level path
# * 073: library dir
# * >>>: no links in header
# * >>>: use of CRLF
copydat mess.patch
expect -2 "Success*30.01%*014*015*025*026*051*055*056*063*063*072*073*073*'>>>'*links*'>>>'*term*" -csi mess.patch
md5cmp eb90cd3f8a3529218677eb04bc799cdd mess.patch
