#!/usr/bin/env bash
dir=$(tmpinit && tmppath dir && echo "${dir}" && [[ -d ${dir} ]]) \
	|| fail "failed to create '${dir}'"
[[ ${dir} == "${PWD}"/* ]] || fail "'${dir}' was expected in '${PWD}'"
[[ ! -d ${dir} ]] || fail "'${dir}' was not deleted on exit"

dir=$(tmpinit -n && tmppath dir && echo "${dir}" && [[ -d ${dir} ]]) \
	|| fail "failed to create '${dir}'"
[[ -d ${dir} ]] || fail "'${dir}' was not supposed to be deleted on exit"
