# Either symlink, copy, or source using /etc/portage/bashrc to load everything.
# Assumes not already using post_pkg_*(), adjust if needed (just an example).

if \
	. "@datadir@/qa-cmp.bashrc" &&
	. "@datadir@/qa-openrc.bashrc" &&
	. "@datadir@/qa-sed.bashrc" &&
	. "@datadir@/qa-vdb.bashrc"; then
	post_pkg_preinst() {
		qa-cmp_post_pkg_preinst
		qa-openrc_post_pkg_preinst
	}

	post_pkg_postinst() {
		qa-vdb_post_pkg_postinst
	}
fi

# vim: ts=4 ft=ebuild
