# symlink, copy, or source using /etc/portage/bashrc to load all features

if \
	. "@datadir@/filelist-diff.bashrc" &&
	. "@datadir@/soname-diff.bashrc" &&
	. "@datadir@/qa-sed.bashrc" &&
	. "@datadir@/qa-vdb.bashrc"; then
	post_pkg_preinst() {
		filelist-diff_post_pkg_preinst
		soname-diff_post_pkg_preinst
	}

	post_pkg_postinst() {
		filelist-diff_post_pkg_postinst
		soname-diff_post_pkg_postinst
		qa-vdb_post_pkg_postinst
	}
fi

# vim: ts=4 ft=ebuild
