#!/usr/bin/env bash

REPOPATH=${DATADIR}/repo:${PWD}/alt
mkdir -p alt/profiles
echo alt > alt/profiles/repo_name

expect "*/repo" -c1P "${REPOPATH}"
echo junk | expect "*/repo" -cP "${REPOPATH}"
echo 2 | expect "*/alt" -cP "${REPOPATH}"
echo 3 | expect "*/repo" -cP "${REPOPATH}"
