#!/usr/bin/env bash

REPOPATH=${DATADIR}/repo:${PWD}/alt
mkdir -p alt/profiles
echo alt > alt/profiles/repo_name

expect "*/repo" -cr1P "${REPOPATH}"
echo junk | expect "*/repo" -crP "${REPOPATH}"
echo 2 | expect "*/alt" -crP "${REPOPATH}"
echo 3 | expect "*/repo" -crP "${REPOPATH}"
