#!/usr/bin/env bash
# should understand that "file" is the input despite other args having files,
# and to do so expressions change nothing only in the right file (gives QA)
echo text > file
echo rep > 50
echo 's/rep/bad/;s/text/new/' > exp
expect -2 "SED:*" -l 50 --line-length 50 -f exp file -isuffix --file exp --expression s/new/text/ --in-place='' --in-place -e s/rep/bad/
