#!/usr/bin/env bash
testfunc() {
	false \
		false \
			false || die
}
expect -c -s -2 "*'
  003:     false \\
  004:         false \\
  005:             false || die
  ^^^ testfunc:5'*" xfail -s 1 testfunc

expect -c -2 "Error:*test message*" xfail -s 1 die test message

# subshell has a special meaning for hook_end, so prevent exit to run without
end_func=$(declare -f end)
eval "${end_func//exit/return}"
testhook=
hook_end() { testhook=y; }
( die ) || :
[[ ${testhook} != y ]] || fail "hook_end was ran when it shouldn't"
die || :
[[ ${testhook} == y ]] || fail "hook_end was not ran when it should"
