#!/usr/bin/env bash
testfunc() {
	false \
		false \
			false || die
}
expect -c -s -2 "*'
  003:     false \\
  004:         false \\
  005:             false || die
  ^^^ testfunc:5'*" xfail -s 1 testfunc

expect -c -2 "Error:*test message*" xfail -s 1 die test message

hook_end() {
	echo hook >&2
}
expect -c -2 "Error:*test*hook*" xfail -s 1 die test
