#!/usr/bin/env bash
expect -c -s "'expect -c -s '*%s" showline 2 "${BASH_SOURCE[0]}" %s
expect \
	-c \
	-s \
	"*'003(expect \\)'*'004(    -c \\)'*'005(    -s \\)'*'%03d(%s)'*" showline 6 "${BASH_SOURCE[0]}" '%03d(%s)'
