#!/usr/bin/env bash
. "${0%/*}"/../lib/common.bashlib || exit 1 #C#
init
depend getopt
include atomf
usage <<-EOU
	Usage: ${0##*/} [format] <atom(s)...>

	Format <atom> based on [format], or return 9 elements separated by
	spaces if a single atom with no format specified.

	atom can be in dependency-format, e.g. !!>=cat/name-1.2.3-r1:*/0=[use],
	but [use] will be discarded.

	atom can be incomplete, but will return 1 if single elements are seen as
	invalid per the Package Manager Specification (PMS).

	Options:
	  -x, --expand       Ignore format and expand multiple atoms to elements
	  -s, --unset=STR    When expanding, show STR if unset (default: '?')
	  -v, --versplit     Split a version string into elements instead
	                     (no characters are dropped for versions)

	      --confdir=PATH Configuration dir to use instead of defaults
	                     (@confdir@ + ${XDG_CONFIG_HOME:-~/.config}/@package@)
	      --dumpconfig   Display configuration and exit

	  -h, --help         Display usage information and exit
	      --version      Display version information and exit

	*Format*
	 0.  %! Blocker indicator (!, !!, or none)
	 1.  %o Version range operator (>=, >, etc... or none)
	 2.  %c Category
	 3.  %n Name
	 4.  %v Version
	 5.  %r Revision (as -rN, or none)
	 6.  %s Slot (as :0, or none)
	 7.  %u Subslot (as /0, or none)
	 8.  %b Binding operator (= or none)
	 -.  %% Literal %
	e.g. "%c/%n-%v%r" = category/name-1.0-r1

	 -.  %p Equivalent to %c/%n
	 -.  %e Equivalent to %v%r
	 -.  %f Equivalent to %c/%n-%v%r

	%R,%S,%U alternatively display %r,%s,%u without prefixes, and as 0 if unset.

	If one of %c, %n, or %v are requested but missing from atom, will report
	error for this atom and exit with return status 2.

	*Notes*
	If need to use this in a bash script extensively, it is recommended to source
	@datadir@/atomf.bashlib directly rather than call this.
EOU
optauto args "${@}" <<-EOO
	x|expand=bool:false
	s|unset=str:?
	v|versplit=bool:false
EOO
set -- "${args[@]}"; unset args

(( ${#} )) || die "no format/atom specified, see \`${0##*/} --help\`"

exiterrno=
if ${O[versplit]}; then
	while (( ${#} )); do
		if pversp ver "${1}"; then
			echo "${ver[*]}"
		else
			: "${exiterrno:=${?}}"
			err "'${1}' is an invalid version string"
		fi
		shift
	done
elif (( ${#} > 1 )) && ! ${O[expand]}; then
	format=${1}
	shift

	while (( ${#} )); do
		atomf "${format}" "${1}" || {
			errno=${?}
			: "${exiterrno:=${errno}}"
			if (( errno == 2 )); then
				err "'${1}' is missing components"
			else
				err "'${1}' is an invalid atom"
			fi
		}
		shift
	done
else
	while (( ${#} )); do
		if atomsp atom "${1}"; then
			merge=
			for ((i=0; i<${#atom[@]}; i++)); do
				: "${atom[i]:=${O[unset]}}"
				merge+=${atom[i]:+ ${atom[i]}}
			done
			echo "${merge# }"
		else
			: "${exiterrno:=${?}}"
			err "'${1}' is an invalid atom"
		fi
		shift
	done
fi

exit "${exiterrno:-0}"

# vim: ts=4
