#!/usr/bin/env bash
# test - argument to skip emerging new
set_portroot
ebuild "$(get_ebuild test 1.0.0)" merge
ebuild "$(get_ebuild test 1.5.0)" merge
ebuild "$(get_ebuild test 2.0.0)" merge
export EOLDNEW_EMERGE_CMD=echo
expect "*=dev-test/test-1.5.0" - dev-test/test
expect "*=dev-test/test-1.0.0" 2- dev-test/test
xfail 1 expect -2 "*Error: failed to find an older version*" - =dev-test/test-1.0.0
