#!/usr/bin/env bash
set_portroot
touch file{1,2,3}
ebuild "$(get_ebuild test 1.5 bin:file{1,2,3})" merge
ebuild "$(get_ebuild test 2.5 bin:file1 cmd:"insinto /usr/bin; doins '${PWD}'/file2")" install
expect -s "*'
 FILES:-usr/bin/file2 (-rwxr-xr-x '*:*')
 FILES:-usr/bin/file3
 FILES:+usr/bin/file2 (-rw-r--r-- '*:*')
'*'FILES(+1,-2)'*" -c test
expect -s "*'
 FILES:-usr/bin/file3
'*'FILES(-1)'*" -c --ignore-perms test
expect -s "*'
 FILES:-usr/bin/file2 (-rwxr-xr-x '*:*')
 FILES:-usr/bin/file3 (-rwxr-xr-x '*:*')
 FILES:+usr/bin/file2 (-rw-r--r-- '*:*')
'*'FILES(+1,-2)'*" -c --show-perms test

# should become like --ignore-perms if system's files are not readable/missing
rm "${ROOT}"/usr/bin/file2
expect -s "*'
 FILES:-usr/bin/file3
'*'FILES(-1)'*" -c test
