#!/usr/bin/env bash
set_portroot
ebuild "$(get_ebuild libdummy 1.5 lib.so:"${LIBD100}" SLOT:2/1)" merge
ebuild "$(get_ebuild dummy 1.5 bin:"${EXED}" RDEPEND:dev-test/libdummy)" merge
expect "*+dev-test/libdummy:2=" -cUrWx dev-test/dummy
expect "VDB:*expected*" -cUrWx --no-bind --no-slot dev-test/dummy
expect "VDB:*expected*" -cUrWx --exclude-bind=dev-test/libdummy --exclude-slot=dev-test/libdummy dev-test/dummy
ebuild "$(get_ebuild dummy 2.5 bin:"${EXED}" RDEPEND:dev-test/libdummy:2=)" merge
expect "VDB:*expected*" -cUrWsx dev-test/dummy
